name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    outputs:
      instance_id: ${{ steps.terraform.outputs.instance_id }}

    defaults:
      run:
        working-directory: terraform

    steps:     
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897722709473:role/github-actions-deploy
          role-session-name: GitHubActions-Terraform
          audience: sts.amazonaws.com
          aws-region: us-east-1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan

      - name: terraform apply
        run: terraform apply -auto-approve

      - name: terraform outputs
        id: terraform
        run: |
          echo "instance_id=$(terraform output -raw instance_id)" >> "$GITHUB_OUTPUT"
  build:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: build docker image
          run: docker build -t my-html-app ./form

        - name: tag the docker image
          run: docker tag my-html-app ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
  
        - name: login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: push docker image
          run: docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest           


  deploy:
    needs: [terraform, build]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897722709473:role/github-actions-deploy
          role-session-name: GitHubActions-Deploy
          audience: sts.amazonaws.com
          aws-region: us-east-1

      - name: deploy to ec2
        run: |
          aws ssm send-command \
            --instance-ids ${{ needs.terraform.outputs.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
                "docker pull ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest",
                "docker stop my-html-app || true",
                "docker rm my-html-app || true",
                "docker run -d --name my-html-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest"
                ]' \
                --region us-east-1
                   
